In [1]:
!python --version


Python 3.8.10


In [2]:
# Step No :02 Data Gathering

In [3]:
from sklearn.datasets import load_wine

In [4]:
dir(load_wine())

['DESCR', 'data', 'feature_names', 'frame', 'target', 'target_names']

In [5]:
dataset = load_wine()

In [6]:
dataset.feature_names

['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']

In [7]:
dataset.target_names

array(['class_0', 'class_1', 'class_2'], dtype='<U7')

In [8]:
dataset.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [9]:
dataset.frame

In [10]:
import pandas as pd
import numpy as np

In [11]:
df = pd.DataFrame(dataset.data, columns =dataset.feature_names)
df.rename({'od280/od315_of_diluted_wines': 'diluted_wine'}, axis =1 , inplace=True)

In [12]:
df['Wine_Quality'] = dataset.target

In [13]:
df.head(5)

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   diluted_wine  proline  Wine_Quality  
0          3.92   1065.0             0  
1          3.40   1050.0             0  
2          3.17   1185.0             0  
3          3.45   1480.0             0  
4          2.93    735.0             0

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   alcohol               178 non-null    float64
 1   malic_acid            178 non-null    float64
 2   ash                   178 non-null    float64
 3   alcalinity_of_ash     178 non-null    float64
 4   magnesium             178 non-null    float64
 5   total_phenols         178 non-null    float64
 6   flavanoids            178 non-null    float64
 7   nonflavanoid_phenols  178 non-null    float64
 8   proanthocyanins       178 non-null    float64
 9   color_intensity       178 non-null    float64
 10  hue                   178 non-null    float64
 11  diluted_wine          178 non-null    float64
 12  proline               178 non-null    float64
 13  Wine_Quality          178 non-null    int32  
dtypes: float64(13), int32(1)
memory usage: 18.9 KB


In [15]:
df['Wine_Quality'].value_counts()

1    71
0    59
2    48
Name: Wine_Quality, dtype: int64

In [16]:
x = df.drop('Wine_Quality' , axis =1)

In [17]:
y = df['Wine_Quality']

In [18]:
from sklearn.linear_model import LogisticRegression

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
model = LogisticRegression()

In [21]:
x_train ,x_test , y_train ,y_test = train_test_split(x,y ,train_size = 0.7 , random_state= 1 , stratify=y)
x_train.shape ,x_test.shape, y_train.shape ,y_test.shape

((124, 13), (54, 13), (124,), (54,))

In [22]:
model.fit(x_train , y_train)

C:\Users\GhanaPallavi\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [23]:
#Model Evaluation 

In [24]:
model.coef_

array([[-1.71040637e-01,  1.91606584e-01,  1.28108310e-01,
        -3.28208005e-01, -3.08782130e-02,  3.10322250e-01,
         5.97734486e-01, -4.90512931e-02,  2.18946460e-01,
         4.72615527e-02, -3.77086983e-04,  4.12534535e-01,
         1.06591667e-02],
       [ 5.86771666e-01, -7.21721438e-01, -7.20024852e-02,
         2.61709276e-01,  6.31825543e-04,  9.28640637e-02,
         2.69735210e-01,  7.92734712e-02,  1.41174448e-01,
        -1.06514190e+00,  2.36457575e-01,  3.03822608e-01,
        -1.06944516e-02],
       [-4.15731029e-01,  5.30114854e-01, -5.61058250e-02,
         6.64987287e-02,  3.02463875e-02, -4.03186313e-01,
        -8.67469696e-01, -3.02221780e-02, -3.60120907e-01,
         1.01788035e+00, -2.36080488e-01, -7.16357143e-01,
         3.52849539e-05]])

In [25]:
model.intercept_

array([-0.04189544,  0.09954237, -0.05764692])

In [26]:
from sklearn.metrics import accuracy_score ,confusion_matrix,multilabel_confusion_matrix , classification_report

In [27]:
y_pred = model.predict(x_test)

In [28]:
print(accuracy_score(y_test , y_pred))

0.9259259259259259


In [29]:
model.score(x_test ,y_test)

0.9259259259259259

In [30]:
print(classification_report(y_test ,y_pred))

              precision    recall  f1-score   support

           0       0.89      0.94      0.92        18
           1       0.90      0.90      0.90        21
           2       1.00      0.93      0.97        15

    accuracy                           0.93        54
   macro avg       0.93      0.93      0.93        54
weighted avg       0.93      0.93      0.93        54



In [31]:
confusion_matrix(y_test ,y_pred)

array([[17,  1,  0],
       [ 2, 19,  0],
       [ 0,  1, 14]], dtype=int64)

In [32]:
print(multilabel_confusion_matrix(y_test , y_pred))

[[[34  2]
  [ 1 17]]

 [[31  2]
  [ 2 19]]

 [[39  0]
  [ 1 14]]]


In [33]:
df.columns

Index(['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium',
       'total_phenols', 'flavanoids', 'nonflavanoid_phenols',
       'proanthocyanins', 'color_intensity', 'hue', 'diluted_wine', 'proline',
       'Wine_Quality'],
      dtype='object')

In [34]:
dict1 = {'feature_name':['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium',
       'total_phenols', 'flavanoids', 'nonflavanoid_phenols',
       'proanthocyanins', 'color_intensity', 'hue',
       'od280/od315_of_diluted_wines', 'proline']}

In [35]:
import json

In [36]:
with open ('feature.json','w') as file:
    json.dump(dict1 , file)

In [37]:
import pickle
with open ('model.pkl' , 'wb') as file:
    pickle.dump(model , file)

In [38]:
# model prediction

In [39]:
df.head(1).T

0
alcohol                 14.23
malic_acid               1.71
ash                      2.43
alcalinity_of_ash       15.60
magnesium              127.00
total_phenols            2.80
flavanoids               3.06
nonflavanoid_phenols     0.28
proanthocyanins          2.29
color_intensity          5.64
hue                      1.04
diluted_wine             3.92
proline               1065.00
Wine_Quality             0.00

In [43]:
model.predict(x_test)

array([1, 2, 2, 1, 1, 0, 1, 0, 1, 2, 2, 0, 0, 0, 2, 1, 0, 1, 0, 2, 0, 1,
       1, 0, 1, 2, 2, 1, 1, 1, 2, 1, 0, 1, 1, 1, 2, 1, 1, 2, 0, 2, 0, 0,
       0, 0, 0, 2, 1, 0, 1, 0, 0, 2])

In [61]:
list(df.columns)

['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'diluted_wine',
 'proline',
 'Wine_Quality']

In [76]:
alcohol = float(input())
malic_acid =  float(input())
ash = float(input())
alcalinity_of_ash = float(input())
magnesium = float(input())
total_phenols = float(input())
flavanoids = float(input())
nonflavanoid_phenols = float(input())
proanthocyanins = float(input())
color_intensity = float(input())
hue = float(input())
diluted_wine = float(input())
proline = float(input())


import numpy as np

array = np.array([[alcohol ,malic_acid ,ash ,alcalinity_of_ash , magnesium ,total_phenols ,flavanoids ,nonflavanoid_phenols ,
                 proanthocyanins ,color_intensity ,hue ,proline ,proline ]])
print(array)
model.predict(array)

13.52
3.17
2.72
23.5
97
1.55
0.52
0.50
0.55
4.35
0.89
2.06
520
[[1.352e+01 3.170e+00 2.720e+00 2.350e+01 9.700e+01 1.550e+00 5.200e-01
  5.000e-01 5.500e-01 4.350e+00 8.900e-01 5.200e+02 5.200e+02]]


C:\Users\GhanaPallavi\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0])

In [70]:
print(x_test[0:2])

     alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
142    13.52        3.17  2.72               23.5       97.0           1.55   
152    13.11        1.90  2.75               25.5      116.0           2.20   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
142        0.52                  0.50             0.55             4.35  0.89   
152        1.28                  0.26             1.56             7.10  0.61   

     diluted_wine  proline  
142          2.06    520.0  
152          1.33    425.0  


In [71]:
model.predict(x_test[0:2])

array([1, 2])